---
title: "Assignment2-Reproducible Research"
author: Samuel Talle
date: August 22, 2016
output: md_document

---


```{r, echo=TRUE}
#load library
library(sqldf,warn.conflicts = FALSE, quietly = TRUE)
```

```{r, echo=TRUE}
#Code for reading in the dataset and/or processing the data
MyData <- read.csv(file="activity.csv", header=TRUE, sep=",")
MyData$steps<-as.numeric(MyData$steps) # convert steps to numeric
```

```{r, echo=TRUE}
#Histogram of the total number of steps taken each day
TotalStepsEachDay <- sqldf("SELECT date,sum(steps) as totalsteps 
                            FROM MyData  
                                group by date")
TotalStepsEachDay$totalsteps<-as.numeric(TotalStepsEachDay$totalsteps) # convert steps to numeric
hist(TotalStepsEachDay$totalsteps,breaks=10,col = "red")
```

```{r, echo=TRUE}
#Mean and median number of steps taken each day
median(TotalStepsEachDay$totalsteps,na.rm = TRUE)
mean(TotalStepsEachDay$totalsteps,na.rm = TRUE)
```

```{r, echo=TRUE}
#Time series plot of the average number of steps taken
AvgStepsEachDay <- sqldf("SELECT date,avg(steps) as Avgsteps 
                            FROM MyData  
                           group by date")

avgtimeseries <- ts(AvgStepsEachDay$Avgsteps)
plot.ts(avgtimeseries)

```

```{r, echo=TRUE}
#The 5-minute interval that, on average, contains the maximum number of steps
MaxSteps <-sqldf("SELECT max(steps) FROM MyData")
Interval <-sprintf("SELECT interval FROM MyData where steps = %s", MaxSteps)
sqldf(Interval)
```

```{r, echo=TRUE}
#Code to describe and show a strategy for imputing missing data
MyData2<-MyData[complete.cases(MyData),] #remove all records with missing values
```

```{r, echo=TRUE}
#Histogram of the total number of steps taken each day after missing values are imputed
TotalStepsEachDay2 <- sqldf("SELECT date,sum(steps) as totalsteps 
                            FROM MyData2  
                           group by date")
TotalStepsEachDay2$totalsteps<-as.numeric(TotalStepsEachDay2$totalsteps) # convert steps to numeric
hist(TotalStepsEachDay2$totalsteps,breaks=10,col = "red")
```

```{r, echo=TRUE}
#Panel plot comparing the average number of steps taken per 5-minute interval across weekdays and weekends
MyData2$days<-weekdays(as.Date(MyData2$date,'%Y-%m-%d'))

AvgStepsWeekdays <- sqldf("SELECT days,avg(steps) as avgsteps 
                            FROM MyData2 GROUP BY days
                          ")
barplot(AvgStepsWeekdays$avgsteps,names.arg = AvgStepsWeekdays$days)
```
